### ISSUE TITLE
If multiple popover containers are found on page, all are triggered

### ISSUE THREAD

**Issue by designbyadrian** [fraina/react-popupbox#4]
I understand this is an edge case, where I have to implemented this popover multiple times, because how my app is structured, but if you could change your element query to only select the first instance of `.popupbox` this would greatly help.

**Comment by designbyadrian** [comment]
Though I did insert the <PopupboxContainer> element on all views I know one would appear, and removed the reference from all other components. So that's a solution as well.

**Comment by fraina** [comment]
Hi! Sorry for my late reply. The container should be inserted only once, so there should be only one container instance in your app. The content will depend on `open` method's `content` parameter, which is required by default. 

In my use case, when there is a need to implemented the popupbox multiple times with the same content (e.g. a logout message alert box), I will create a function that handle popupbox's open method with correct content (which means logout message for this example), then pass it to the the other components, so that I can simply call the function wherever I need to show the message.

Feel free to let me know if it can't solve your case.

**Comment by fraina** [comment]
Close this issue for now cause there is no more discussion.
