### ISSUE TITLE
Config changes back to defaults on click

### ISSUE THREAD

**Issue by RyanThomas95** [fraina/react-popupbox#5]
Hello! I have this code:
`
render() {
  const popupboxConfig = {
    overlayOpacity: 0.2,
  }
  return (
    <div onClick={this.__handleClick}>
      <img src={icon.trash}/>
      <PopupboxContainer { ...popupboxConfig } />
    </div>
  );
}
`
The popup box renders, but the config changes back to the defaults when I click on the image. Any ideas what could be causing this?

**Comment by fraina** [comment]
Hi, @RyanThomas95. I've been busy for a while, sorry for the late reply.
I just publish `v2.0.2` version to fix the bug you mentioned, thank you so much! 
And I highly recommend move the `<PopupboxContainer \>` outside the `div` which provide `onClick` event, because the event will be called every time you clicking overlay and popupbox.

Feel free to reopen this issue if it can't solve your case. :)
